# Generated by Django 4.1.7 on 2023-02-16 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del Proveedor', max_length=50)),
                ('nit', models.CharField(help_text='NIT', max_length=11, validators=[django.core.validators.RegexValidator('(^[0-9]{9}-{1}[0-9]{1})', 'Just NIT format is allowed')])),
                ('contact_name', models.CharField(help_text='Nombre del contacto', max_length=50)),
                ('contact_phone', models.CharField(help_text='Movil del contacto', max_length=10)),
                ('bank', models.CharField(help_text='Nombre del Banco', max_length=15)),
                ('account_bank', models.CharField(help_text='Numero de cuenta bancaria', max_length=15)),
            ],
        ),
    ]
